# Generated by Django 3.2.4 on 2023-06-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApolloModelL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ApolloModelL2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(max_length=50)),
                ('image2', models.CharField(max_length=50)),
                ('image3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ApolloModelO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.CharField(max_length=50)),
                ('image2', models.CharField(max_length=50)),
                ('image3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ApolloModelO2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ApolloModelP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='', max_length=300)),
                ('insta', models.CharField(max_length=50)),
                ('face', models.CharField(max_length=50)),
                ('twitter', models.CharField(max_length=50)),
                ('pintrest', models.CharField(max_length=50)),
            ],
        ),
    ]
